name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

# env:
#   MONGO_URL: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
#   MONGO_USERNAME: ${{vars.MANGO_USERNAME}}
#   MONGO_PASSWORD: ${{secrets.MANGO_PASSWORD}}

jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongodb:
            image: siddharth67/mongo-db:non-prod
            ports: 
              - 27017:27017
        env:
          MONGO_URL: 'mongodb://localhost:27017/superData'
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password

        strategy:
          matrix:
            nodejs_version: [18,20]
            operating_system: [ubuntu-latest]
        runs-on: ${{matrix.operating_system}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version  --- ${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Caching the depencides for faster pipeline
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{runner.os}}-NodeModules-${{hashFiles('package-lock.json')}}


        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-testing-step
          run: npm test
          
        - name: Archive Test Result.......
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result -- ${{matrix.nodejs_version}}-${{matrix.operating_system}}
            path: ./test-results.xml


    coverage_test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup node js installation
            uses: actions/setup-node@v3
            with:
              node-version: 18  

          - name: Caching the depencides for faster pipeline
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{runner.os}}-NodeModules-${{hashFiles('package-lock.json')}}


          - name: install Dependencies
            run: npm install

          - name: run coverage test
            continue-on-error: true
            run: npm run coverage 

          - name: upload aritifcat
            uses: actions/upload-artifact@v4
            with:
              name: Code-coverage-result
              path: coverage
              retention-days: 5


    Containerization:
      runs-on: ubuntu-latest
      services:
        mongodb:
          image: siddharth67/mongo-db:non-prod
          ports:
          - 27017:27017
      permissions: 
        packages: write
      needs: [coverage_test,unit-testing]
      steps:

        - name : Checkout Repository
          uses: actions/checkout@v4
          
        - name: login into docker
          uses: docker/login-action@v3
          with:
            username: ${{vars.username}}
            password: ${{secrets.dockerpassword}}


        - name: login into github container registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{github.repository_owner}}
            password: ${{secrets.GITHUB_TOKEN}}

        - name: build image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: ${{vars.username}}/solar-system:${{github.sha}}

        - name: running the image and testing it.
          run: |
            docker images
            docker run --name solar-app-system -d \
            -p 3000:3000 \
            -e MONGO_URL='mongodb://localhost:27017/superData' \
            -e MONGO_USERNAME=non-prod-user \
            -e MONGO_PASSWORD=non-prod-password \
            ${{vars.username}}/solar-system:${{github.sha}}

            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-app-system)
            echo $IP

            echo "Waiting for app to start..."
            sleep 5

            echo "Container logs:"
            docker logs solar-app-system

            echo testing image URL using wget
            wget -q -O - http://127.0.0.1:3000/live | grep live

   

        - name: Docker push as well as github container registry push.
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: |
              ${{vars.username}}/solar-system:${{github.sha}}
              ghcr.io/${{github.repository_owner}}/solar-system:${{github.sha}}

    Deployment:
      needs: Containerization
      runs-on: ubuntu-latest
      steps:
        - name: installing kubectl cmd on runner
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.26.0'


        - name: getting all the files through Checkout
          uses: actions/checkout@v4
        - name: installing kubectl CLI on the runner
          uses: azure/setup-kubectl@v4
          with:
            version: 'v1.26.0'

        - name: Login into aws
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Update kubeconfig
          run: aws eks update-kubeconfig --region us-east-1 --name MoizNadeemCluster

        - name: get the k8 cluster details
          run: |
            kubectl version --short
            echo -------------------------------------
            kubectl get nodes



        




