name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URL: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MANGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MANGO_PASSWORD}}

jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            nodejs_version: [18,20]
            operating_system: [ubuntu-latest]
        runs-on: ${{matrix.operating_system}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version  --- ${{matrix.nodejs_version}}
          uses: actions/setup-node@v3
          with:
            node-version: ${{matrix.nodejs_version}}

        - name: Caching the depencides for faster pipeline
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{runner.os}}-NodeModules-${{hashFiles('package-lock.json')}}


        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-testing-step
          run: npm test
          
        - name: Archive Test Result.......
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result -- ${{matrix.nodejs_version}}-${{matrix.operating_system}}
            path: ./test-results.xml


    coverage_test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup node js installation
            uses: actions/setup-node@v3
            with:
              node-version: 18  

          - name: Caching the depencides for faster pipeline
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{runner.os}}-NodeModules-${{hashFiles('package-lock.json')}}


          - name: install Dependencies
            run: npm install

          - name: run coverage test
            continue-on-error: true
            run: npm run coverage 

          - name: upload aritifcat
            uses: actions/upload-artifact@v4
            with:
              name: Code-coverage-result
              path: coverage
              retention-days: 5
    docker_login:
      runs-on: ubuntu-latest
      needs: [coverage_test,unit-testing]
      steps:
        - name: login into docker
          uses: docker/login-action@v3
          with:
            username:${{vars.username}}
            password:${{secrets.dockerpassword}}